import { Component, OnInit } from "@angular/core";
import { Observable } from "rxjs";
import { debounceTime, distinctUntilChanged, map } from "rxjs/operators";

const states = [
  "Karachi",
  "Lahore",
  "Faisalābād",
  "Serai",
  "Rāwalpindi",
  "Multān",
  "Gujrānwāla",
  "Hyderābād City",
  "Peshāwar",
  "Abbottābād",
  "Islamabad",
  "Quetta",
  "Bannu",
  "Bahāwalpur",
  "Sargodha",
  "Siālkot City",
  "Sukkur",
  "Lārkāna",
  "Sheikhupura",
  "Mīrpur Khās",
  "Rahīmyār Khān",
  "Kohāt",
  "Jhang Sadr",
  "Gujrāt",
  "Bardār",
  "Kasūr",
  "Dera Ghāzi Khān",
  "Masīwāla",
  "Nawābshāh",
  "Okāra",
  "Gilgit",
  "Chiniot",
  "Sādiqābād",
  "Turbat",
  "Dera Ismāīl Khān",
  "Chaman",
  "Zhob",
  "Mehra",
  "Parachinār",
  "Gwādar",
  "Kundiān",
  "Shahdād Kot",
  "Harīpur",
  "Matiāri",
  "Dera Allāhyār",
  "Lodhrān",
  "Batgrām",
  "Thatta",
  "Bāgh",
  "Badīn",
  "Mānsehra",
  "Ziārat",
  "Muzaffargarh",
  "Tando Allāhyār",
  "Dera Murād Jamāli",
  "Karak",
  "Mardan",
  "Uthal",
  "Nankāna Sāhib",
  "Bārkhān",
  "Hāfizābād",
  "Kotli",
  "Loralai",
  "Dera Bugti",
  "Jhang City",
  "Sāhīwāl",
  "Sānghar",
  "Pākpattan",
  "Chakwāl",
  "Khushāb",
  "Ghotki",
  "Kohlu",
  "Khuzdār",
  "Awārān",
  "Nowshera",
  "Chārsadda",
  "Qila Abdullāh",
  "Bahāwalnagar",
  "Dādu",
  "Alīābad",
  "Lakki Marwat",
  "Chilās",
  "Pishin",
  "Tānk",
  "Chitrāl",
  "Qila Saifullāh",
  "Shikārpur",
  "Panjgūr",
  "Mastung",
  "Kalāt",
  "Gandāvā",
  "Khānewāl",
  "Nārowāl",
  "Khairpur",
  "Malakand",
  "Vihāri",
  "Saidu Sharif",
  "Jhelum",
  "Mandi Bahāuddīn",
  "Bhakkar",
  "Toba Tek Singh",
  "Jāmshoro",
  "Khārān",
  "Umarkot",
  "Hangu",
  "Timargara",
  "Gākuch",
  "Jacobābād",
  "Alpūrai",
  "Miānwāli",
  "Mūsa Khel Bāzār",
  "Naushahro Fīroz",
  "New Mīrpur",
  "Daggar",
  "Eidgāh",
  "Sibi",
  "Dālbandīn",
  "Rājanpur",
  "Leiah",
  "Upper Dir",
  "Tando Muhammad Khān",
  "Attock City",
  "Rāwala Kot",
  "Swābi",
  "Kandhkot",
  "Dasu",
  "Athmuqam",
];

@Component({
  selector: "app-location-search-box",
  templateUrl: "./location-search-box.component.html",
  styleUrls: ["./location-search-box.component.scss"],
})
export class LocationSearchBoxComponent implements OnInit {
  public model: any;

  search = (text$: Observable<string>) =>
    text$.pipe(
      debounceTime(200),
      distinctUntilChanged(),
      map((term) =>
        term.length < 2
          ? []
          : states
              .filter((v) => v.toLowerCase().indexOf(term.toLowerCase()) > -1)
              .slice(0, 10)
      )
    );
  constructor() {}

  ngOnInit(): void {}
}
